version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pos

  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./redis_data:/data
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 4000:4000
    depends_on:
      - postgres
      # - redis
    networks:
      - pos
    volumes:
      - ./server/src/:/app/src/
      - ./uploads:/app/uploads
  # web:
  #   build: ./web
  #   ports:
  #     - 5173:5173
networks:
  pos:
    driver: bridge
