version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./redis_data:/data
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      # - redis
    # command: ./docker-entrypoint.sh
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    container_name: web
    restart: unless-stopped
    # environment:
    #   VITE_API_URL: http://localhost:6000/api/v1

    ports:
      - "3000:80"
